// Dishonored VR - unity translation unit (Phase 1 of the refactor).
//
// The mod was one 23k-line file. tools/split-source.py cut it into the module
// tree below without changing a single function body: state (includes, types,
// globals) in the original order, then a prototype for every function, then
// the bodies grouped by subsystem. Everything is still ONE translation unit
// with the same static linkage, so the program is byte-for-byte the same;
// later phases give each module its own header and translation unit and
// drop it from this list.
//
// Line numbers in comments and docs refer to the original single file (src/dllmain.cpp at commit 48766c07, proxy build 38.92).

// ---- state: includes, types, globals, macros (original order) ----------
#include "mod/state/00_mod_prelude.inc"
#include "mod/state/01_proxy_proxy_state.inc"
#include "mod/state/02_legacy_vs_scan.inc"
#include "mod/state/03_core_vr_openvr_backend.inc"
#include "mod/state/04_core_gfx_d3d11_device.inc"
#include "mod/state/05_core_gfx_d3d9_capture.inc"
#include "mod/state/06_game_dishonored_head_track.inc"
#include "mod/state/07_game_dishonored_patterns.inc"
#include "mod/state/08_game_dishonored_fov_lever.inc"
#include "mod/state/09_legacy_spacebases.inc"
#include "mod/state/10_legacy_rtd_drive.inc"
#include "mod/state/11_core_gfx_hand_mesh.inc"
#include "mod/state/12_game_dishonored_hands_skelcontrol.inc"
#include "mod/state/13_game_dishonored_game_state.inc"
#include "mod/state/14_core_util_log.inc"
#include "mod/state/15_core_config_config.inc"
#include "mod/state/16_core_gfx_d3d11_device.inc"
#include "mod/state/17_core_gfx_eye_quads.inc"
#include "mod/state/18_core_gfx_hand_mesh.inc"
#include "mod/state/19_core_gfx_d3d11_device.inc"
#include "mod/state/20_core_window_game_window.inc"
#include "mod/state/21_core_gfx_hud_panel.inc"
#include "mod/state/22_core_gfx_present.inc"
#include "mod/state/23_game_dishonored_ue3_uobject.inc"
#include "mod/state/24_game_dishonored_head_track.inc"
#include "mod/state/25_legacy_camera_tracer.inc"
#include "mod/state/26_legacy_fire_tracer.inc"
#include "mod/state/27_game_dishonored_motion_aim.inc"
#include "mod/state/28_legacy_aim_watch.inc"
#include "mod/state/29_game_dishonored_motion_aim.inc"
#include "mod/state/30_legacy_fp_mesh.inc"
#include "mod/state/31_legacy_camera_hook.inc"
#include "mod/state/32_game_dishonored_head_track.inc"
#include "mod/state/33_game_dishonored_ue3_uobject.inc"
#include "mod/state/34_legacy_fp_mesh.inc"
#include "mod/state/35_game_dishonored_ue3_uobject.inc"
#include "mod/state/36_legacy_fp_mesh.inc"
#include "mod/state/37_game_dishonored_hands_fp_mesh.inc"
#include "mod/state/38_legacy_rtd_drive.inc"
#include "mod/state/39_game_dishonored_hands_fp_mesh.inc"
#include "mod/state/40_game_dishonored_hands_arms_hide.inc"
#include "mod/state/41_game_dishonored_ue3_uobject.inc"
#include "mod/state/42_game_dishonored_crouch.inc"
#include "mod/state/43_game_dishonored_hands_skelcontrol.inc"
#include "mod/state/44_game_dishonored_blink.inc"
#include "mod/state/45_game_dishonored_hands_skelcontrol.inc"
#include "mod/state/46_legacy_cam_seam.inc"
#include "mod/state/47_core_window_res_spoof.inc"
#include "mod/state/48_legacy_cam_seam.inc"
#include "mod/state/49_game_dishonored_head_track.inc"
#include "mod/state/50_game_dishonored_fov_lever.inc"
#include "mod/state/51_legacy_spacebases.inc"
#include "mod/state/52_game_dishonored_head_track.inc"
#include "mod/state/53_core_input_pad_bridge.inc"
#include "mod/state/54_core_window_res_spoof.inc"
#include "mod/state/55_core_input_pad_bridge.inc"
#include "mod/state/56_core_framework_frame_hooks.inc"
#include "mod/state/57_core_window_res_spoof.inc"
#include "mod/state/58_core_framework_frame_hooks.inc"
#include "mod/state/59_core_vr_openxr_loader.inc"
#include "mod/state/60_core_vr_openxr_backend.inc"
#include "mod/state/61_core_vr_openxr_input.inc"
#include "mod/state/62_proxy_dllmain.inc"

// ---- every function, so the bodies below can be in any order --------------
#include "mod/fwd.h"

// ---- function bodies by subsystem -------------------------------------------
#include "core/config/config.cpp"
#include "core/framework/frame_hooks.cpp"
#include "core/gfx/d3d11_device.cpp"
#include "core/gfx/eye_quads.cpp"
#include "core/gfx/hand_mesh.cpp"
#include "core/gfx/hud_panel.cpp"
#include "core/gfx/present.cpp"
#include "core/hooks/iat.cpp"
#include "core/hooks/vtable.cpp"
#include "core/input/hotkeys.cpp"
#include "core/input/pad_bridge.cpp"
#include "core/ui/overlay.cpp"
#include "core/util/clock.cpp"
#include "core/util/crash.cpp"
#include "core/util/ini.cpp"
#include "core/util/log.cpp"
#include "core/util/mem.cpp"
#include "core/vr/openvr_backend.cpp"
#include "core/vr/openxr_backend.cpp"
#include "core/vr/openxr_input.cpp"
#include "core/vr/openxr_loader.cpp"
#include "core/vr/openxr_pace.cpp"
#include "core/window/game_window.cpp"
#include "core/window/res_spoof.cpp"
#include "game/dishonored/blink.cpp"
#include "game/dishonored/blink_stubs.cpp"
#include "game/dishonored/block_state.cpp"
#include "game/dishonored/console.cpp"
#include "game/dishonored/crouch.cpp"
#include "game/dishonored/fov_lever.cpp"
#include "game/dishonored/game_state.cpp"
#include "game/dishonored/hands/arms_hide.cpp"
#include "game/dishonored/hands/fp_mesh.cpp"
#include "game/dishonored/hands/graft.cpp"
#include "game/dishonored/hands/hand_pose.cpp"
#include "game/dishonored/hands/skelcontrol.cpp"
#include "game/dishonored/head_track.cpp"
#include "game/dishonored/melee.cpp"
#include "game/dishonored/motion_aim.cpp"
#include "game/dishonored/shared/ue_math.cpp"
#include "game/dishonored/ue3/process_event.cpp"
#include "game/dishonored/ue3/uobject.cpp"
#include "legacy/aim_watch.cpp"
#include "legacy/cam_seam.cpp"
#include "legacy/camera_hook.cpp"
#include "legacy/camera_tracer.cpp"
#include "legacy/fire_tracer.cpp"
#include "legacy/fp_mesh.cpp"
#include "legacy/ovl_scene.cpp"
#include "legacy/rtd_drive.cpp"
#include "legacy/spacebases.cpp"
#include "legacy/ue3_probe.cpp"
#include "legacy/vs_scan.cpp"
#include "legacy/xr_bench.cpp"
#include "proxy/d3d9_exports.cpp"
#include "proxy/dllmain.cpp"
